url: http://pbogut.me
menu:
  -
    title: Home
    url: /
  -
    title: Portfolio
    url: /portfolio.html
  -
    title: Sketch
    url: /sketch.html
    menu: "posts"

social:
  -
    name: linkedin
    url: https://uk.linkedin.com/pub/pawel-bogut/91/48a/b76
    sign: "&#57417;"
  -
    name: github
    url: https://github.com/pbogut
    sign: "&#57392;"
  -
    name: stackoverflow
    url: https://stackoverflow.com/users/story/752006
    sign: "&#57351;"
