url: http://pbogut.me
menu:
  -
    title: Home
    url: /
  -
    title: Portfolio
    url: /portfolio.html

social:
  -
    name: linkedin
    url: http://uk.linkedin.com/pub/pawe%C5%82-bogut/91/48a/b76
    sign: "&#57417;"
  -
    name: github
    url: https://github.com/pbogut
    sign: "&#57392;"
  -
    name: stackoverflow
    url: http://stackoverflow.com/users/story/752006
    sign: "&#57351;"
