url: http://pbogut.me
menu:
  -
    name: Home
    url: /
  -
    name: Portfolio
    url: /portfolio.html
  -
    name: Apps
    url: /apps.html
    menu:
      -
        name: Chrome App Shortcut Generator
        url: http://casg.smeagol.pl/

social:
  -
    name: linkedin
    url: http://uk.linkedin.com/pub/pawe%C5%82-bogut/91/48a/b76
    sign: "&#57417;"
  -
    name: github
    url: https://github.com/pbogut
    sign: "&#57392;"
  -
    name: stackoverflow
    url: http://stackoverflow.com/users/story/752006
    sign: "&#57351;"
