[[companies]]
name = "Axolit"
image = "/images/work/axolit.png"
position = "Founder / Developer"
period = "2018 - Present"
description = """
With a focus on web development and expertise in PHP, Magento, JavaScript,
and Elixir. I provide customized solutions to meet the specific requirements of
my clients.
"""
skills = ["php", "javascript", "elixir", "rust", "magento"]

[[companies]]
name = "Assured Pharmacy"
image = "/images/work/assuredpharmacy.png"
position = "Lead Developer"
period = "2018 - Present"
description = """
I managed and improved a comprehensive pharmacy management system, ensuring
smooth operations and patient management. Additionally, I migrated the Magento 1
storefront to Magento 2 and continue to work on Magento improvements.
"""
skills = ["php", "magento2", "laravel", "tailwind", "docker", "mariadb"]


[[companies]]
name = "UK POS"
image = "/images/work/ukpos.png"
position = "Senior Developer"
period = "2016 - 2018"
description = """
I have developed a Data Warehouse application that combines data from different
sources (applications) and utilizes data analysis techniques to extract valuable
insights and generate comprehensive reports. I have also assisted in improving
the Magento store.
"""
skills = ["php", "magento", "laravel", "docker", "mysql"]

[[companies]]
name = "Monocore"
image = "/images/work/monocore.png"
position = "Senior Developer"
period = "2014 - 2016"
description = """
I maintained two Magento shops, with a focus on creating new modules to enhance
functionality. In addition, I designed and implemented internal applications
for reporting, streamlining processes, and enhancing efficiency.
"""
skills = ["php", "magento", "javascript", "mysql"]

[[companies]]
name = "Web-Soft.com.pl"
image = "/images/work/websoft.png"
position = "Junior / Mid Developer"
period = "2012 - 2014"
description = """
Initially, I was responsible for maintaining current projects and adding new
functionalities. Later, I focused on creating new projects and Magento
modules.
"""
skills = ["php", "magento", "javascript", "zendframework", "extjs", "mysql"]
